# Generated by Django 4.2.6 on 2023-10-07 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_dp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dp',
            old_name='ame',
            new_name='name',
        ),
    ]
